Implemented search functionality
iislom-babaev/steam_app_khumoyiddin pull request #6
Opened 2023-01-12 07:35 UTC by Khumoyiddin

[//]: # (Feel free to remove parts that do not relate to the changes you are willing to bring into main)

### Search bar
[//]: # (Give a brief summary of why the change is being implemented, i.e. feature was built, bug fixing and etc.)

### Changes
[//]: # (List change details here for Code Reviewers)
1. Added search bar in storyboard
2. Implemented search functionality

2023-01-16 11:18 UTC, AbboskhonShukurullaev requested changes
Keyboard is not hiding

2023-01-16 11:39 UTC, AbboskhonShukurullaev commented
When you tap on the screen, you should firstly hide the keyboard, the next tap is to push the viewController. The same behavior should be applied everywhere.

2023-01-16 11:43 UTC, AbboskhonShukurullaev commented
Clear button is not visible 

<img width="49" alt="Screenshot 2023-01-16 at 16 42 34" src="https://user-images.githubusercontent.com/45316460/212670483-27a393cb-e945-4cc6-a07d-8f2715576a50.png">

2023-01-16 11:59 UTC, AbboskhonShukurullaev commented on steam_app/controllers/FavoritesViewController.swift
> +    var filteredData = [Favorite]()
it's a bad approach to put an instance of the Game inside the array as the array will never be empty.
Better to put it this way var filteredData: [Favorite] = []

2023-01-16 11:59 UTC, AbboskhonShukurullaev commented on steam_app/controllers/Games/GamesViewController.swift
> +    var filteredData = [Game]()
it's a bad approach to put an instance of the Game inside the array as the array will never be empty.
Better to put it this way var filteredData: [Game] = []

2023-01-16 11:59 UTC, AbboskhonShukurullaev commented on steam_app/controllers/News/NewsViewController.swift
> +    var filteredData = [News]()
it's a bad approach to put an instance of the Game inside the array as the array will never be empty.
Better to put it this way var filteredData: [News] = []

2023-01-17 06:38 UTC, AbboskhonShukurullaev commented
It's better to clear textField after you pushed to the next view controller

<img width="423" alt="Screenshot 2023-01-17 at 11 36 57" src="https://user-images.githubusercontent.com/45316460/212826829-1981e240-ef4f-497e-ad4e-96c277208d1e.png">

2023-01-17 06:41 UTC, AbboskhonShukurullaev commented
Let's say you want to access to the cells below the keyboard. Right now you cannot access it because you either need to hide the keyboard first or scroll the content below the keyboard. 
My approach would be to allow the user access all the content below the keyboard via scrollView

<img width="383" alt="Screenshot 2023-01-17 at 11 38 35" src="https://user-images.githubusercontent.com/45316460/212827130-e09b49bb-70dc-4b02-932e-0c64f57541b5.png">

2023-01-23 11:42 UTC, abubakrj commented on steam_app/FavoritesTableView/FavoritesTableViewCell.swift
> +        let favs = data[indexPath.row]
I would suggest to give more concrete names here like below:
```Swift
func configureCell(with game: Game) {
}
```

The cell should now know about other objects and also, it does not need to know about the index path as well

2023-01-23 11:42 UTC, abubakrj commented on steam_app/GamesTableView/GamesTableViewCell.swift
> +        let game = data[indexPath.row]
Same here with the naming conventions

2023-01-23 11:42 UTC, abubakrj commented on steam_app/NewsTableView/NewsTableViewCell.swift
> +        let news = data[indexPath.row]
Same here

2023-01-23 11:42 UTC, abubakrj commented on steam_app/SearchBar.swift
> +    func configureCustomSearchBar(searchBar: UISearchBar) {
Since this is an extension, you don't need to pass the search bar object, you could directly use self

2023-01-23 11:42 UTC, abubakrj commented on steam_app/controllers/News/NewsViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide(notification:)), name: UIResponder.keyboardWillHideNotification, object: nil)
This configuration should not be in the configure table view method

2023-01-23 11:42 UTC, abubakrj commented on steam_app/controllers/News/NewsViewController.swift
> +    @IBOutlet weak var search: UISearchBar!
`search` sounds more like a method name rather than a view. `searchBar` would fit more correctly

2023-01-23 11:42 UTC, abubakrj commented on steam_app/controllers/Games/GamesViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(keyboardWillHide(notification:)), name: UIResponder.keyboardWillHideNotification, object: nil)
Same here

2023-01-25 05:39 UTC, merged